Removed installed hook + added github action

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -5,11 +5,45 @@ set -eux
 
 function snap_logging () {
     SNAP_ACTIONS_LOG_DIR="/etc/systemd/system/snap.${PROJECT_NAME}.daemon.service.d/logs"
+    mkdir -p "${SNAP_ACTIONS_LOG_DIR}"
 
     script_log="${SNAP_ACTIONS_LOG_DIR}/$1.log"
     exec 1>>"${script_log}"
     exec 2>&1
 }
+
+# ----------------------------
+
+function systemd_override () {
+    DAEMON_SYSTEMD_PATH="/etc/systemd/system/snap.${PROJECT_NAME}.daemon.service.d"
+    mkdir -p "${DAEMON_SYSTEMD_PATH}"
+
+    # We are copying the service conf file patch as editing the service file generated by snapd won't survive upgrades
+    cp "${SNAP}"/etc/systemd/override.conf "${DAEMON_SYSTEMD_PATH}"/
+}
+
+function system_conf_override () {
+    # 1. Set the number of open file handles
+    # ulimit -n 1024 -- default in local machine
+    ulimit -n 65535
+
+    # 2. Allow the opensearch user to Disable all swap files:
+    # swapon -a -- default in local machine
+    swapoff -a || true
+
+    # 3. Ensuring sufficient virtual memory: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
+    # sysctl -w vm.max_map_count=65530 -- default in local machine
+    sysctl -w vm.max_map_count=262144
+
+    # 4. number of threads opensearch can create:
+    # should be configured automatically if opensearch ran as a service
+
+    # 5. Reduce TCP retransmission timeout = ~6 seconds
+    # sysctl -w net.ipv4.tcp_retries2=15 -- default in local machine
+    sysctl -w net.ipv4.tcp_retries2=5
+}
+
+# -------------------------------
 
 function set_access_restrictions () {
     if [[ $# -eq 2 ]]; then
@@ -51,10 +85,16 @@ function set_property () {
     sed -i "s@$2@$3@" "$1"
 }
 
+# -------------------------------
 
-snap_logging "hook-configure"
+# snap_logging "hook-configure"
 
+systemd_override
+system_conf_override
 
+# -------------------------------
+
+# Opensearch install folders and set config
 dir_copy_if_not_exists "bin" "${SNAP_DATA}" 770
 dir_copy_if_not_exists "jdk" "${SNAP_DATA}" 770
 dir_copy_if_not_exists "lib" "${SNAP_DATA}" 550
